stages:
  - build
  - deployToAws

build:
  image: docker
  services:
    - docker:dind
  stage: build
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker build --pull -t "$CI_REGISTRY_IMAGE:frontgrupoa" .
    - docker push "$CI_REGISTRY_IMAGE:frontgrupoa"

deployToAws:
  stage: deployToAws
  image: alpine
  variables:
    SERVER: 18.223.110.94
    PORT: 84
  script:
    - apk add openssh
    - apk add bash
    - mkdir ~/.ssh
    - echo "$SSH_KNOWN_HOSTS_AWS" >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    # add ssh key stored in SSH_PRIVATE_KEY variable to the agent store
    - eval $(ssh-agent -s)
    - bash -c 'ssh-add <(echo "$SSH_PRIVATE_KEY_AWS")'
    # log into Docker registry
    - ssh ubuntu@$SERVER "echo $CI_BUILD_TOKEN | docker login --username gitlab-ci-token --password-stdin registry.gitlab.com"
    # stop container, remove image.
    - ssh ubuntu@$SERVER "docker container stop frontgrupoa" || true
    - ssh ubuntu@$SERVER "docker container rm frontgrupoa" || true
    - ssh ubuntu@$SERVER "docker image rm ${CI_REGISTRY_IMAGE}:frontgrupoa" || true
    # start new container
    - ssh ubuntu@$SERVER "docker container run --name frontgrupoa -p $PORT:5000 -d ${CI_REGISTRY_IMAGE}:frontgrupoa"
